obstacle_range: 2.5
raytrace_range: 3.0
radius: 0.4
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, data_type: LaserScan, topic: laser, marking: true, clearing: true}
